name: "Unit and Build Tests"

on:
  push:
  pull_request:
    branches: [ master ]


jobs:
  build-test:
    runs-on: "ubuntu-latest"

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.19

    - name: "Build & test"
      run: "make tools test cross_compile"

    - name: Upload build artifacts
      uses: actions/upload-artifact@v3
      with:
        name: binaries
        path: builds/pkg/*/gotty