---
name: "tagged-release"

on:
  push:
    tags:
      - "v*"

permissions:
  contents: write

jobs:
  tagged-release:
    name: "Tagged Release"
    runs-on: "ubuntu-latest"

    steps:
    - uses: actions/checkout@v7
      with:
        fetch-depth: 0

    - name: Set up Go
      uses: actions/setup-go@v7
      with:
        go-version-file: go.mod

    - name: "Build & test"
      run: "make tools test release-artifacts"

    - name: Upload build artifacts
      uses: actions/upload-artifact@v7
      with:
        name: binaries
        path: builds/pkg/*/gotty

    - name: "Create draft release"
      uses: softprops/action-gh-release@v3
      with:
        token: "${{ secrets.GITHUB_TOKEN }}"
        draft: true
        prerelease: false
        generate_release_notes: true
        files: |
          LICENSE
          builds/dist/*
